### PR TITLE
Re-index elements before export

### LINKED ISSUE #9: PNML Export no longer compatible with Renew
## Describe the bug
The new generated ID format (e.g. `shape-6vhjfr-4hsv5k61`) throws a `NumberFormatException` when parsed by Renew.

## To Reproduce
1. Draw anything
2. Export to PNML
3. Import in latest Renew
4. See `java.lang.NumberFormatException`

## Expected behavior
Even though the PNML is still valid according to spec our main goal is compatibility with Renew so it should be able to import the files we generate.

## Additional context
Simply re-indexing all elements in the PnmlSerializer should do the trick.

### PR DESCRIPTION
**Pull request by 0x4d**
Closes #9 

- Use for loop to loop over elements
- Use loop index + 1 as new ID (must not start at 0)
- Create a map of old to new IDs for replacing connection references

### CODE REVIEW

File: src/serializers/PnmlSerializer.js [hunk 1]
```diff
@@ -2,6 +2,7 @@ export default class PnmlSerializer {
 
     constructor () {
         this.xmlSerializer = new XMLSerializer();
+        this.idMap = {};
```
Comment (tim-kilian) [inline src/serializers/PnmlSerializer.js:5]: why not `this.ids`?

File: src/serializers/PnmlSerializer.js [hunk 2]
```diff
@@ -11,10 +12,13 @@ export default class PnmlSerializer {
         netElement.setAttribute('id', 'net_' + Date.now());
         netElement.setAttribute('type', ns);
 
-        data.elements.forEach((element) => {
-            const classifierEl = this.createClassifierElement(element, doc);
-            netElement.appendChild(classifierEl);
-        });
+        for (let i = 0; i < data.elements.length; i++) {
+            this.idMap[data.elements[i].id] = i + 1;
```
Comment (tim-kilian) [inline src/serializers/PnmlSerializer.js:16]: Dont renew go [1, n] than [0, n]?

**Review by tim-kilian — APPROVED** [review]

**Comment by tim-kilian** [comment]
Waiting for you response, you can merge it yourself. I'll publish a new version afterwards.

File: src/serializers/PnmlSerializer.js (hunk 1 above)
Comment (0x4d) [reply src/serializers/PnmlSerializer.js:5]: Because it's used as a map. :laughing:

File: src/serializers/PnmlSerializer.js (hunk 2 above)
Comment (tim-kilian) [reply src/serializers/PnmlSerializer.js:16]: Nevermind, there is a +1

File: src/serializers/PnmlSerializer.js (hunk 1 above)
Comment (tim-kilian) [reply src/serializers/PnmlSerializer.js:5]: But its still an object. There is no map in JavaScript :D

Comment (tim-kilian) [reply src/serializers/PnmlSerializer.js:5]: Ah, sry, my mistake, there is a Map in JavaScript, but this is just an Object.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

Comment (0x4d) [reply src/serializers/PnmlSerializer.js:5]: Everything in JS is just an object. :smile: And because of this I see no harm in using the variable name to hint at the objects semantics ...

Comment (tim-kilian) [reply src/serializers/PnmlSerializer.js:5]: idc, I'll merge and publish it.

**Comment by tim-kilian** [comment]
Published https://www.npmjs.com/package/renew-formalism-pt
