### PR TITLE
Fix connection labels

### LINKED ISSUE #16: Add arc inscriptions
Currently arcs only have `pt:name` type labels.

Another type of label `pt:inscription` should be added to be able to define arc multiplicity.

### LINKED ISSUE #19: Get bbox of arcs (layoutConnection?)
https://github.com/renew-js/renew-formalism-pt/blob/30f33d41d40ebe17655b337693f09d3ee8f8a6dd/src/parsers/PnmlParser.js#L122-L127

---

###### This issue was generated by [todo](https://todo.jasonet.co) based on a `TODO` comment in 30f33d41d40ebe17655b337693f09d3ee8f8a6dd when #17 was merged. cc @renew-js.

### PR DESCRIPTION
**Pull request by 0x4d**
Closes #16 
Closes #19 

- Create connections before labels
- Add parent element to label
- Add fix for bendpoint connections

## TODO
- [x] Add inscription context pad tool icon

### CODE REVIEW

File: src/parsers/PnmlParser.js [hunk 1]
```diff
@@ -163,8 +165,8 @@ export default class PnmlParser {
     sortElements () {
         const sortOrder = {
             'shape': 0,
-            'label': 1,
-            'connection': 2,
+            'connection': 1,
+            'label': 2,
```
Comment (tim-kilian) [inline src/parsers/PnmlParser.js:169]: Why you changed the sort order?

**Review by tim-kilian — APPROVED** [review]
